config/routes.rb
DoubleACms::Application.routes.draw do
  get "dashboard/index"

  root :to => "home#index"
 localized(I18n.available_locales, :verbose => true) do 
    namespace :admin do
      root :to => "dashboard#index"
      resource  :dashboard, :only => [:index]
      resources :settings, :only => [:index, :update]
      resources :users 
      resources :pages 
    end
    
    devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }
    match 'login', :to => 'devise/sessions#new'
    match 'logout', :to  => 'devise/sessions#destroy'
 end
  

end

app/views/admin/pages/_form.html.haml
= form_for [:admin, @page] do |f|
  = render 'shared/error_messages' , :target => @page
  %p
    = f.label :title
    %br
    = f.text_field :title
  %p
    = f.label :content
    %br
    = f.text_area :content, :class => "tinymce"
  %p
    = button_submit_tag button
    = danger_button_link_to t("cancel"), admin_users_url

app/views/admin/pages/edit.html.haml
= render 'form', :button => t("update")

app/views/admin/pages/index.html.haml
= button_group do
  = add_button_link_to t("new", :model => t("models.page.name")), new_admin_page_url
  = search_button_link_to t("search"), new_admin_page_url
%table
  %tr
    %th Title
    %th Content
    %th Created at
    %th 
  - @pages.each do |page| 
    %tr
      %td= link_to page.title, [:admin, page]
      %td= strip_words(page.content, 5)
      %td= page.created_at.to_s(:db)
      %td
        = button_group do
          = edit_button_link_to t("edit"), edit_admin_page_path(page) 
          = trash_danger_button_link_to t("destroy"), [:admin, page], :confirm => "Are you sure?", :method => :delete

app/views/admin/pages/new.html.haml
= render 'form', :button => t("create")

app/views/admin/pages/show.html.haml
%h1= @page.title

.body_content
  =raw @page.content