config/routes.rb
DoubleACms::Application.routes.draw do
  get "dashboard/index"

  root :to => "home#index"
 localized(I18n.available_locales, :verbose => true) do 
    namespace :admin do
      root :to => "dashboard#index"
      resource  :dashboard, :only => [:index]
      resources :settings, :only => [:index, :update]
      resources :users 
      resources :pages 
    end
    
    devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }
    match 'login', :to => 'devise/sessions#new'
    match 'logout', :to  => 'devise/sessions#destroy'
 end
  

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActivityLog
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  field :name, type: String
  field :admin, type: Boolean
end

app/controllers/admin/users_controller.rb
# -*- encoding : utf-8 -*-
class Admin::UsersController < Admin::ApplicationController
  before_filter :find_user, :only => [:edit, :update, :destroy] 
  
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = t("notice.successfully.created", :model => t("models.user.name").capitalize)
      redirect_to admin_users_path
    else
      render :action => :new
    end
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:notice] = t("notice.successfully.updated", :model => t("models.user.name").capitalize)
      redirect_to admin_users_path
    else
      render :action => :edit
    end
  end

  def destroy
    @user.destroy
    flash[:notice] = t("notice.successfully.destroyed", :model => t("models.user.name").capitalize)
    redirect_to(admin_users_path)
  end

  protected
  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def user_type(user)
    user.admin? ? "Admin" : "Staff" 
  end
end

app/views/admin/users/_form.html.haml
= form_for [:admin, @user] do |f|
  = render "/shared/error_messages", :target => @user
  %p
    = f.label :name
    %br
    = f.text_field :name
  %p
    = f.label :email
    %br
    = f.text_field :email
  %p
    = f.label :password
    %br
    = f.password_field :password
  %p
    =f.check_box :admin
    =f.label :admin
  %p
    = approve_button_submit_tag button
    = danger_button_link_to t("cancel"), admin_users_url

app/views/admin/users/edit.html.haml
= render 'form', :button => t("update")

app/views/admin/users/index.html.haml
= button_group do
  = add_button_link_to t("new", :model => t("models.user.name")), new_admin_user_url
  = search_button_link_to t("search"), new_admin_user_url
%table
  %tr
    %th E-mail
    %th Name
    %th Type
    %th Created at
    %th 
  - @users.each do |user| 
    %tr
      %td= user.email
      %td= user.name
      %td= user_type(user)
      %td= user.created_at.to_s(:db)
      %td
        
        = button_group do
          = edit_button_link_to t("edit"), edit_admin_user_path(user) 
          = trash_danger_button_link_to t("destroy"), [:admin, user], :confirm => "Are you sure?", :method => :delete

app/views/admin/users/new.html.haml
= render 'form', :button => t("create")