config/routes.rb
DoubleACms::Application.routes.draw do
  get "dashboard/index"

  root :to => "home#index"
 localized(I18n.available_locales, :verbose => true) do 
    namespace :admin do
      root :to => "dashboard#index"
      resource  :dashboard, :only => [:index]
      resources :settings, :only => [:index, :update]
      resources :users 
      resources :pages 
    end
    
    devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }
    match 'login', :to => 'devise/sessions#new'
    match 'logout', :to  => 'devise/sessions#destroy'
 end
  

end

app/views/layouts/admin.html.haml
!!!
%html
  = render 'shared/html_head_admin'
  %body
    %header
      %h1 AA CMS
      %nav.main
        = link_to(image_tag(gravatar_url_for(current_user.email)))
        %span
          = welcome(current_user)
          %span 
            |
          = link_to t("dashboard"), admin_root_url
          %span 
            |
          = link_to t("settings"), admin_settings_url
        
        .logout= arrowright_danger_button_link_to t("logout"), logout_url
      .clear
        
    %nav#navbar
      = button_group do
        = admin_menu_item(:pages)
        = admin_menu_item(:users)
      
    = breadcrumb

    %section#content
      = show_notice
      = yield
    %footer
      = link_to "AA Tecnologia", "http://www.aatecnologia.com.br", :target => "_blank"
    
    = javascript_include_tag :defaults
    = javascript_include_tag "libs/jquery.tinymce.js"
    = javascript_include_tag "editor.js"

app/views/layouts/application.html.haml
!!!
%html
  = render 'shared/html_head'
  %body
    = yield
    = javascript_include_tag :defaults
    = google_analytics